### ISSUE TITLE
Will this work on RPi 2 or Zero W?

### ISSUE THREAD

**Issue by greencane** [sergge1/opencv_rpi#1]
Thank you sergge1 for this code.  It worked perfectly on my PRi 4.  I tried to recreate the steps on a RPi 2 and an RPi Zero W.  Both fail when trying to check the CV2 version.

 pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 89, in <module>
    bootstrap()
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 79, in bootstrap
    import cv2
ImportError: libtesseract.so.4: cannot open shared object file: No such file or directory
>>>_

**Comment by greencane** [comment]
I can confirm this does not work for a Pi2 or PiZero.  I did however successfully build openCV for both of those platforms following Will's instructions (PiZero needed a minor modification to comment out NEON and VFPV3).  https://gist.github.com/willprice/abe456f5f74aa95d7e0bb81d5a710b60
